
create table order_wash_items(
   ORDER_NUMBER nvarchar(32) NULL,
   WASH_ITEM_ID INT NOT NULL,
   COUNT INT NOT NULL,
   CREATE_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE `order_wash_items` ADD INDEX `ORDER_WASH_ITEMS_ORDER_NUMBER_INDX` (`ORDER_NUMBER`);
