USE washita_2016;

ALTER TABLE `orders` ADD COLUMN `PICKUP_FROM` TIMESTAMP NOT NULL;
ALTER TABLE `orders` ADD COLUMN `PICKUP_TILL` TIMESTAMP NOT NULL;



ALTER TABLE `orders` ADD INDEX `ORDER_PICKUP_INDX` (`PICKUP_FROM`,`PICKUP_TILL`);