--DROP TABLE IF EXISTS `users`;

create table users(
   ID int primary key NOT NULL AUTO_INCREMENT,
   EMAIL varchar(124) NOT NULL,
   NOTIFICATION_EMAIL varchar(124) NOT NULL,
   PASSWORD varchar(512) NOT NULL,
   NAME nvarchar(256) NOT NULL,
   LASTNAME nvarchar(256) NOT NULL,
   IS_COMPLETE BIT(1) NOT NULL DEFAULT 0,
   FIRST_FAILED_LOGIN_TIME INT UNSIGNED NOT NULL DEFAULT 0,
   FAILED_LOGIN_COUNT INT UNSIGNED NOT NULL DEFAULT 0,
   CREATE_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE `users` ADD INDEX `USERS_EMAIL_INDX` (`EMAIL`);
