


ALTER TABLE `users` ADD `AUTH_PROVIDER_NAME` VARCHAR(255) NULL COMMENT 'Provider name';
ALTER TABLE `users` ADD `AUTH_PROVIDER_UID` VARCHAR(255) NULL COMMENT 'Provider user ID';
 
CREATE UNIQUE INDEX USERS_AUTH_PROVIDER_UNIQUE_INDX ON users (AUTH_PROVIDER_NAME, AUTH_PROVIDER_UID);
 
ALTER TABLE `users` ADD INDEX `USERS_AUTH_PROVIDER_UID_INDX` (`AUTH_PROVIDER_UID`);
