


ALTER TABLE `orders` ADD `IS_FEEDBACK_REQUESTED` BOOL NOT NULL DEFAULT 0 COMMENT 'Is email sent';

ALTER TABLE `orders` ADD `FEEDBACK_CODE` varchar(40) NULL;
ALTER TABLE `orders` ADD INDEX `ORDERS_FEEDBACK_CODE_INDX` (`FEEDBACK_CODE`);


