
-- add actual weight
ALTER TABLE `orders` ADD COLUMN `ACTUAL_WEIGHT` decimal NULL;
ALTER TABLE `orders` ADD COLUMN `ADDITIONAL_PRICE_WITHOUT_DISCOUNT` decimal NULL;
ALTER TABLE `orders` ADD COLUMN `ADDITIONAL_PRICE_WITH_DISCOUNT` decimal NULL;
